### ISSUE TITLE
Exporting dash to html gives hexadecimal code

### ISSUE THREAD

**Issue by RCoeurjoly** [zacwood9/.emacs.d#1]
I publish (M+x org-publish-project) the following to html:

#+OPTIONS: toc:nil num:nil

#+BEGIN_EXPORT html
---
layout: post
title: "A beginner's Emacs config"
subtitle: "First steps into the Emacs universe"
tags: [hacking, emacs]
category: blog
---
#+END_EXPORT

I get the following:

<div class="export">
<p>
&#x2014;
layout: post
title: "A beginner's Emacs config"
subtitle: "First steps into the Emacs universe"
tags: [hacking, emacs]
category: blog
&#x2014;
</p>

I expect the following:

---
layout: post
title: "A beginner's Emacs config"
subtitle: "First steps into the Emacs universe"
tags: [hacking, emacs]
category: blog
---

I learn that &#x2014 is the hexadecimal code for a dash (-).
As a result of the previously described behaviour, my blog doesn't
display the html. Like a all.

As you can see, I tried with one of your headers to see if I had something wrong with mine.

Exporting one of your org posts gives me a html file different from yours, so the bug must be in the export function. 

However I have the same options in the config of emacs.

I have reported the bug to the org-mode mailing list

**Comment by zacwood9** [comment]
I noticed in your post to the mailing list the name of your project is this:
`org-publish-project-alist '(("https://rcoeurjoly.github.io/posts" ...`

I have had issues in the past when my project name contained the `/` character. In my config now, my blog project is named `"zacwood.me.posts"`. Maybe try replacing all the `/` characters in your project name with `.`. This worked for me.

**Comment by RCoeurjoly** [comment]
This issue got solved installing the latest version of org from Elpa.

Changing the '/' character for a '.' solved another problem, namely that of creating folders for caches and temporary things.

Thank you very much!
